return {
	InGame = {
		['286090429'] = {
			Title    = 'Arsual v.52',
			Author   = 'fr¿eze08',
			Callback = function()
				pcall(function()
					loadstring(game:HttpGet('https://raw.githubusercontent.com/usernil01101/JGS-SDD/refs/heads/main/cache%20/Arsenal/Arsual.luau', true))()
				end)
			end,
		},

		['10449761463'] = { 
			{
				Title    = 'Trashcan Man',
				Author   = 'yes1nt',
				Callback = function()
					pcall(function()
						loadstring(game:HttpGet('https://raw.githubusercontent.com/usernil01101/JGS-SDD/refs/heads/main/cache%20/Strongest%20Battlegrounds/Trashcan%20Man.luau', true))()
					end)
				end,
			},
			{
				Title    = 'Standupe',
				Author   = 'dh_0dk36',
				Callback = function()
					pcall(function()
						loadstring(game:HttpGet('https://raw.githubusercontent.com/usernil01101/JGS-SDD/refs/heads/main/cache%20/Strongest%20Battlegrounds/Standupe.luau', true))()
					end)
				end,
			},
		},
	},

	Universal = {
		{
			Title    = 'Infinite Yield',
			Author   = 'EdgeIY',
			Image    = 'rbxasset://textures/explosion.png',
			Callback = function()
				loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source', true))()
			end,
		},
		{
			Title    = 'Fling All',
			Author   = 'meth0x01',
			Image    = 'rbxasset://textures/explosion.png',
			Callback = function()
				loadstring(game:HttpGet('https://raw.githubusercontent.com/usernil01101/JGS-SDD/refs/heads/main/cache%20/Universe/flingall.luau', true))()
			end,
		},
		{
			Title    = 'Invisible',
			Author   = 'meth0x01',
			Image    = 'rbxasset://textures/explosion.png',
			Callback = function()
				loadstring(game:HttpGet('https://raw.githubusercontent.com/usernil01101/JGS-SDD/refs/heads/main/cache%20/Universe/invisiblev1.luau', true))()
			end,
		},
	},
}
